const gamesPage = {
  id: "games",
  title: "games",
  html: `
    <h1>Games</h1>

 <a href="javascript:(function(){var w=window.open('about:blank','_blank');if(!w){alert('Popup blocked');return;}w.moveTo(0,0);w.resizeTo(screen.width,screen.height);w.focus();w.document.write('<!DOCTYPE html><html><head><title>minecraft</title><style>html,body{margin:0;height:100%;overflow:hidden;background:black;}</style></head><body><iframe src=&quot;https://file.garden/ZtNXqbPCZ1cAh6MT/EaglercraftX_1.8_u53_Offline_Signed.html&quot; style=&quot;width:100%;height:100%;border:none;&quot; allowfullscreen></iframe><script>document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen();<\/script></body></html>');w.document.close();})();"> Eaglercraft (opens in about:blank) </a>
    
    <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/baldi/index.html'); return false;">
      Baldi's Basics
    </a>

    <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/wbwwb-master/index.html'); return false;">
      We Become What We Behold (tw: gore)
    </a>

    <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/badtimesimulator/index.html'); return false;">
      Bad Time Simulator (Sans Fight)
    </a>

     <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/flash/html/nyancatlostinspace.html'); return false;">
     Nyan Cat: Lost in Space (tw: mentions of drugs)
    </a>

 <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/doom/dos.html'); return false;">
    DOOM (tw: gore)
    </a>

     <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/flash/html/HappyWheels.html'); return false;">
    Happy Wheels (tw: extreme gore)
    </a>

    <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/4.2.3/index.html'); return false;">
Multi-console game emulator    
</a>

    <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/4.2.3/index.html?rom=Scribblenauts%20Collection%20(USA).nds'); return false;">
Scribblenauts/Super Scribblenauts  
</a>

 <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/4.2.3/index.html?rom=Street%20Fighter%20II%20(Japan).sfc'); return false;">
Street Fighter II: The World Warrior (Japan)

</a>

 <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/flash/html/fridaynightfunkin.html'); return false;">
Friday Night Funkin (Macromedia Flash ver.)

</a>



  <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/ovo/index.html'); return false;">
OVO
</a>

 <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/stickman-hook-unblocked-main/stickman-hook-unblocked-main/index.html'); return false;">
Stickman Hook
</a>

 <a href="#" class="game-link" onclick="launchGame('https://file.garden/ZtNXqbPCZ1cAh6MT/stickman-hook-unblocked-main/stickman-hook-unblocked-main/index.html'); return false;">
Stickman Hook
</a>


 <a href="#" class="game-link" onclick="blobOpen('PHNjcmlwdCBhc3luYyBzcmM9Imh0dHBzOi8vd3d3Lmdvb2dsZXRhZ21hbmFnZXIuY29tL2d0YWcvanM/aWQ9Ry1MNzg1NlAzVk5UIj48L3NjcmlwdD4NCjxzY3JpcHQ+DQogIHdpbmRvdy5kYXRhTGF5ZXIgPSB3aW5kb3cuZGF0YUxheWVyIHx8IFtdOw0KICBmdW5jdGlvbiBndGFnKCl7ZGF0YUxheWVyLnB1c2goYXJndW1lbnRzKTt9DQogIGd0YWcoJ2pzJywgbmV3IERhdGUoKSk7DQoNCiAgZ3RhZygnY29uZmlnJywgJ0ctTDc4NTZQM1ZOVCcpOw0KPC9zY3JpcHQ+PCFET0NUWVBFIGh0bWw+DQo8aHRtbCBsYW5nPSJlbiI+DQogIDxoZWFkPg0KICAgIDxiYXNlIGhyZWY9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9naC93ZWItcG9ydHMvcmFsZGlAbWFpbi8iPg0KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPg0KICAgIDx0aXRsZT5CQUxESTwvdGl0bGU+DQogICAgPGxpbmsgcmVsPSJzaG9ydGN1dCBpY29uIiBocmVmPSJUZW1wbGF0ZURhdGEvZmF2aWNvbi5pY28iIC8+DQogICAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJUZW1wbGF0ZURhdGEvc3R5bGUuY3NzIiAvPg0KICAgIDxtZXRhDQogICAgICBuYW1lPSJ2aWV3cG9ydCINCiAgICAgIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaGVpZ2h0PWRldmljZS1oZWlnaHQsIGluaXRpYWwtc2NhbGU9MS4wIg0KICAgIC8+DQogIDxzdHlsZT4NCiNzaWRlYmFyYWQxLA0KI3NpZGViYXJhZDIgew0KICBwb3NpdGlvbjogZml4ZWQ7DQogIHRvcDogNTAlOw0KICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTUwJSk7DQogIHdpZHRoOiAxNjBweDsNCiAgaGVpZ2h0OiA2MDBweDsNCiAgcGFkZGluZzogMDsNCiAgbWFyZ2luOiAwOw0KICB6LWluZGV4OiA5OTk5OTk7DQp9DQojc2lkZWJhcmFkMSB7DQogIGxlZnQ6IDA7DQp9DQojc2lkZWJhcmFkMiB7DQogIHJpZ2h0OiAwOw0KfQ0KLnNpZGViYXItY2xvc2Ugew0KICBwb3NpdGlvbjogYWJzb2x1dGU7DQogIHRvcDogMDsNCiAgcmlnaHQ6IDA7DQogIHdpZHRoOiAyMnB4Ow0KICBoZWlnaHQ6IDIycHg7DQogIGxpbmUtaGVpZ2h0OiAyMnB4Ow0KICB0ZXh0LWFsaWduOiBjZW50ZXI7DQogIGJhY2tncm91bmQ6IHJnYmEoMCwwLDAsMC43KTsNCiAgY29sb3I6ICNmZmY7DQogIGZvbnQtc2l6ZTogMTRweDsNCiAgY3Vyc29yOiBwb2ludGVyOw0KICB1c2VyLXNlbGVjdDogbm9uZTsNCiAgei1pbmRleDogMTA7DQp9DQouc2lkZWJhci1mcmFtZSB7DQogIHdpZHRoOiAxNjBweDsNCiAgaGVpZ2h0OiA2MDBweDsNCiAgYm9yZGVyOiBub25lOw0KICBkaXNwbGF5OiBibG9jazsNCn0NCjwvc3R5bGU+DQo8L2hlYWQ+DQogIDxib2R5Pg0KPGRpdg0KICBpZD0ibG9hZGluZy10ZXh0Ig0KICBzdHlsZT0iDQogICAgY29sb3I6IHdoaXRlOw0KICAgIGJhY2tncm91bmQtY29sb3I6IGJsYWNrOw0KICAgIGZvbnQtc2l6ZTogNDhweDsNCiAgICBmb250LWZhbWlseTogY3Vyc2l2ZTsNCiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7DQogICAgbWFyZ2luLXRvcDogMjBweDsNCiAgIg0KPg0KICBMT0FESU5HLi4uDQo8L2Rpdj4NCg0KICAgIDxkaXYgaWQ9InVuaXR5LWNvbnRhaW5lciIgY2xhc3M9InVuaXR5LWRlc2t0b3AiPg0KICAgICAgPGNhbnZhcyBpZD0idW5pdHktY2FudmFzIiB3aWR0aD0iOTYwIiBoZWlnaHQ9IjYwMCI+PC9jYW52YXM+DQogICAgICA8ZGl2IGlkPSJ1bml0eS1sb2FkaW5nLWJhciI+DQogICAgICAgIDxkaXYgaWQ9InVuaXR5LWxvZ28iPjwvZGl2Pg0KICAgICAgICA8ZGl2IGlkPSJ1bml0eS1wcm9ncmVzcy1iYXItZW1wdHkiPg0KICAgICAgICAgIDxkaXYgaWQ9InVuaXR5LXByb2dyZXNzLWJhci1mdWxsIj48L2Rpdj4NCiAgICAgICAgPC9kaXY+DQogICAgICA8L2Rpdj4NCiAgICA8L2Rpdj4NCiAgICA8c2NyaXB0Pg0KICAgICAgY29uc3QgbG9hZGluZ1RleHQgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjbG9hZGluZy10ZXh0Iik7DQogICAgICBsZXQgdG90YWxCeXRlcyA9IDI0NDQyOTUyNTsNCiAgICAgIGxldCBsb2FkZWRCeXRlcyA9IDA7DQoNCiAgICAgIGZ1bmN0aW9uIGZvcm1hdFNpemUoYnl0ZXMpIHsNCiAgICAgICAgaWYgKGJ5dGVzID4gMTAyNCAqIDEwMjQgKiAxMDI0KSB7DQogICAgICAgICAgcmV0dXJuIChieXRlcyAvICgxMDI0ICogMTAyNCAqIDEwMjQpKS50b0ZpeGVkKDIpICsgIiBHQiI7DQogICAgICAgIH0gZWxzZSBpZiAoYnl0ZXMgPiAxMDI0ICogMTAyNCkgew0KICAgICAgICAgIHJldHVybiAoYnl0ZXMgLyAoMTAyNCAqIDEwMjQpKS50b0ZpeGVkKDIpICsgIiBNQiI7DQogICAgICAgIH0gZWxzZSBpZiAoYnl0ZXMgPiAxMDI0KSB7DQogICAgICAgICAgcmV0dXJuIChieXRlcyAvIDEwMjQpLnRvRml4ZWQoMikgKyAiIEtCIjsNCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICByZXR1cm4gYnl0ZXMgKyAiIEIiOw0KICAgICAgICB9DQogICAgICB9DQogICAgICBhc3luYyBmdW5jdGlvbiBmZXRjaFdpdGhQcm9ncmVzcyh1cmwpIHsNCiAgICAgICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmwpOw0KICAgICAgICBjb25zdCByZWFkZXIgPSByZXNwb25zZS5ib2R5LmdldFJlYWRlcigpOw0KICAgICAgICBsZXQgY2h1bmtzID0gW107DQogICAgICAgIGxldCByZWNlaXZlZCA9IDA7DQogICAgICAgIHdoaWxlICh0cnVlKSB7DQogICAgICAgICAgY29uc3QgeyBkb25lLCB2YWx1ZSB9ID0gYXdhaXQgcmVhZGVyLnJlYWQoKTsNCiAgICAgICAgICBpZiAoZG9uZSkgYnJlYWs7DQogICAgICAgICAgcmVjZWl2ZWQgKz0gdmFsdWUubGVuZ3RoOw0KICAgICAgICAgIGxvYWRlZEJ5dGVzICs9IHZhbHVlLmxlbmd0aDsNCiAgICAgICAgICBjaHVua3MucHVzaCh2YWx1ZSk7DQogICAgICAgICAgY29uc3QgZG9uZVRleHQgPSBmb3JtYXRTaXplKGxvYWRlZEJ5dGVzKTsNCiAgICAgICAgICBjb25zdCB0b3RhbFRleHQgPSBmb3JtYXRTaXplKHRvdGFsQnl0ZXMpOw0KICAgICAgICAgIGNvbnN0IHBlcmNlbnQgPQ0KICAgICAgICAgICAgdG90YWxCeXRlcyA+IDANCiAgICAgICAgICAgICAgPyAoKGxvYWRlZEJ5dGVzIC8gdG90YWxCeXRlcykgKiAxMDApLnRvRml4ZWQoMSkNCiAgICAgICAgICAgICAgOiAiPyI7DQogICAgICAgICAgbG9hZGluZ1RleHQudGV4dENvbnRlbnQgPSBgTE9BRElORy4uLiAke2RvbmVUZXh0fSAvICR7dG90YWxUZXh0fSAoJHtwZXJjZW50fSUpYDsNCiAgICAgICAgfQ0KICAgICAgICBsZXQgZnVsbEJ1ZmZlciA9IG5ldyBVaW50OEFycmF5KHJlY2VpdmVkKTsNCiAgICAgICAgbGV0IG9mZnNldCA9IDA7DQogICAgICAgIGZvciAobGV0IGNodW5rIG9mIGNodW5rcykgew0KICAgICAgICAgIGZ1bGxCdWZmZXIuc2V0KGNodW5rLCBvZmZzZXQpOw0KICAgICAgICAgIG9mZnNldCArPSBjaHVuay5sZW5ndGg7DQogICAgICAgIH0NCiAgICAgICAgcmV0dXJuIGZ1bGxCdWZmZXIuYnVmZmVyOw0KICAgICAgfQ0KICAgICAgYXN5bmMgZnVuY3Rpb24gbWVyZ2VGaWxlcyhwYXJ0cykgew0KICAgICAgICBjb25zdCBidWZmZXJzID0gYXdhaXQgUHJvbWlzZS5hbGwocGFydHMubWFwKGZldGNoV2l0aFByb2dyZXNzKSk7DQogICAgICAgIHJldHVybiBVUkwuY3JlYXRlT2JqZWN0VVJMKG5ldyBCbG9iKGJ1ZmZlcnMpKTsNCiAgICAgIH0NCg0KICAgICAgZnVuY3Rpb24gZ2V0UGFydHMoZmlsZSwgY291bnQpIHsNCiAgICAgICAgbGV0IHBhcnRzID0gW107DQogICAgICAgIGZvciAobGV0IGkgPSAxOyBpIDw9IGNvdW50OyBpKyspIHsNCiAgICAgICAgICBwYXJ0cy5wdXNoKGZpbGUgKyAiLnBhcnQiICsgaSk7DQogICAgICAgIH0NCiAgICAgICAgcmV0dXJuIHBhcnRzOw0KICAgICAgfQ0KICAgICAgKGFzeW5jICgpID0+IHsNCiAgICAgICAgY29uc3QgZGF0YVBhcnRzID0gZ2V0UGFydHMoIkJ1aWxkL0JBTERJLmRhdGEiLCAxMCk7DQogICAgICAgIGNvbnN0IHdhc21QYXJ0cyA9IGdldFBhcnRzKCJCdWlsZC9CQUxESS53YXNtIiwgMik7DQogICAgICAgIGNvbnN0IFtkYXRhVXJsLCB3YXNtVXJsXSA9IGF3YWl0IFByb21pc2UuYWxsKFsNCiAgICAgICAgICBtZXJnZUZpbGVzKGRhdGFQYXJ0cyksDQogICAgICAgICAgbWVyZ2VGaWxlcyh3YXNtUGFydHMpLA0KICAgICAgICBdKTsNCiAgICAgICAgdmFyIGNvbnRhaW5lciA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiN1bml0eS1jb250YWluZXIiKTsNCiAgICAgICAgdmFyIGNhbnZhcyA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiN1bml0eS1jYW52YXMiKTsNCiAgICAgICAgdmFyIGxvYWRpbmdCYXIgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktbG9hZGluZy1iYXIiKTsNCiAgICAgICAgdmFyIHByb2dyZXNzQmFyRnVsbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoDQogICAgICAgICAgIiN1bml0eS1wcm9ncmVzcy1iYXItZnVsbCINCiAgICAgICAgKTsNCiAgICAgICAgdmFyIHdhcm5pbmdCYW5uZXIgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjdW5pdHktd2FybmluZyIpOw0KDQogICAgICAgIC8vIFNob3dzIGEgdGVtcG9yYXJ5IG1lc3NhZ2UgYmFubmVyL3JpYmJvbiBmb3IgYSBmZXcgc2Vjb25kcywgb3INCiAgICAgICAgLy8gYSBwZXJtYW5lbnQgZXJyb3IgbWVzc2FnZSBvbiB0b3Agb2YgdGhlIGNhbnZhcyBpZiB0eXBlPT0nZXJyb3InLg0KICAgICAgICAvLyBJZiB0eXBlPT0nd2FybmluZycsIGEgeWVsbG93IGhpZ2hsaWdodCBjb2xvciBpcyB1c2VkLg0KICAgICAgICAvLyBNb2RpZnkgb3IgcmVtb3ZlIHRoaXMgZnVuY3Rpb24gdG8gY3VzdG9taXplIHRoZSB2aXN1YWxseSBwcmVzZW50ZWQNCiAgICAgICAgLy8gd2F5IHRoYXQgbm9uLWNyaXRpY2FsIHdhcm5pbmdzIGFuZCBlcnJvciBtZXNzYWdlcyBhcmUgcHJlc2VudGVkIHRvIHRoZQ0KICAgICAgICAvLyB1c2VyLg0KICAgICAgICBmdW5jdGlvbiB1bml0eVNob3dCYW5uZXIobXNnLCB0eXBlKSB7fQ0KDQogICAgICAgIHZhciBidWlsZFVybCA9ICJCdWlsZCI7DQogICAgICAgIHZhciBsb2FkZXJVcmwgPSBidWlsZFVybCArICIvQkFMREkubG9hZGVyLmpzIjsNCiAgICAgICAgdmFyIGNvbmZpZyA9IHsNCiAgICAgICAgICBkYXRhVXJsOiBkYXRhVXJsLA0KICAgICAgICAgIGZyYW1ld29ya1VybDogIkJ1aWxkL0JBTERJLmZyYW1ld29yay5qcyIsDQogICAgICAgICAgY29kZVVybDogd2FzbVVybCwNCiAgICAgICAgICBzdHJlYW1pbmdBc3NldHNVcmw6ICJTdHJlYW1pbmdBc3NldHMiLA0KICAgICAgICAgIGNvbXBhbnlOYW1lOiAiVW5rbm93biIsDQogICAgICAgICAgcHJvZHVjdE5hbWU6ICJCQUxESSIsDQogICAgICAgICAgcHJvZHVjdFZlcnNpb246ICIxLjAiLA0KICAgICAgICB9Ow0KDQogICAgICAgIC8vIEJ5IGRlZmF1bHQgVW5pdHkga2VlcHMgV2ViR0wgY2FudmFzIHJlbmRlciB0YXJnZXQgc2l6ZSBtYXRjaGVkIHdpdGgNCiAgICAgICAgLy8gdGhlIERPTSBzaXplIG9mIHRoZSBjYW52YXMgZWxlbWVudCAoc2NhbGVkIGJ5IHdpbmRvdy5kZXZpY2VQaXhlbFJhdGlvKQ0KICAgICAgICAvLyBTZXQgdGhpcyB0byBmYWxzZSBpZiB5b3Ugd2FudCB0byBkZWNvdXBsZSB0aGlzIHN5bmNocm9uaXphdGlvbiBmcm9tDQogICAgICAgIC8vIGhhcHBlbmluZyBpbnNpZGUgdGhlIGVuZ2luZSwgYW5kIHlvdSB3b3VsZCBpbnN0ZWFkIGxpa2UgdG8gc2l6ZSB1cA0KICAgICAgICAvLyB0aGUgY2FudmFzIERPTSBzaXplIGFuZCBXZWJHTCByZW5kZXIgdGFyZ2V0IHNpemVzIHlvdXJzZWxmLg0KICAgICAgICAvLyBjb25maWcubWF0Y2hXZWJHTFRvQ2FudmFzU2l6ZSA9IGZhbHNlOw0KDQogICAgICAgIGlmICgvaVBob25lfGlQYWR8aVBvZHxBbmRyb2lkL2kudGVzdChuYXZpZ2F0b3IudXNlckFnZW50KSkgew0KICAgICAgICAgIC8vIE1vYmlsZSBkZXZpY2Ugc3R5bGU6IGZpbGwgdGhlIHdob2xlIGJyb3dzZXIgY2xpZW50IGFyZWEgd2l0aCB0aGUgZ2FtZSBjYW52YXM6DQogICAgICAgICAgdmFyIG1ldGEgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJtZXRhIik7DQogICAgICAgICAgbWV0YS5uYW1lID0gInZpZXdwb3J0IjsNCiAgICAgICAgICBtZXRhLmNvbnRlbnQgPQ0KICAgICAgICAgICAgIndpZHRoPWRldmljZS13aWR0aCwgaGVpZ2h0PWRldmljZS1oZWlnaHQsIGluaXRpYWwtc2NhbGU9MS4wLCB1c2VyLXNjYWxhYmxlPW5vLCBzaHJpbmstdG8tZml0PXllcyI7DQogICAgICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoImhlYWQiKVswXS5hcHBlbmRDaGlsZChtZXRhKTsNCiAgICAgICAgfQ0KDQogICAgICAgIHZhciBzY3JpcHQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJzY3JpcHQiKTsNCiAgICAgICAgc2NyaXB0LnNyYyA9IGxvYWRlclVybDsNCiAgICAgICAgc2NyaXB0Lm9ubG9hZCA9ICgpID0+IHsNCiAgICAgICAgICBjcmVhdGVVbml0eUluc3RhbmNlKGNhbnZhcywgY29uZmlnLCAocHJvZ3Jlc3MpID0+IHsNCiAgICAgICAgICAgIHByb2dyZXNzQmFyRnVsbC5zdHlsZS53aWR0aCA9IDEwMCAqIHByb2dyZXNzICsgIiUiOw0KICAgICAgICAgIH0pDQogICAgICAgICAgICAudGhlbigodW5pdHlJbnN0YW5jZSkgPT4gew0KICAgICAgICAgICAgICBjb25zb2xlLmxvZyhsb2FkZWRCeXRlcyk7DQogICAgICAgICAgICAgIGxvYWRpbmdUZXh0LnJlbW92ZSgpOw0KICAgICAgICAgICAgICBsb2FkaW5nQmFyLnN0eWxlLmRpc3BsYXkgPSAibm9uZSI7DQogICAgICAgICAgICB9KQ0KICAgICAgICAgICAgLmNhdGNoKChtZXNzYWdlKSA9PiB7DQogICAgICAgICAgICAgIGFsZXJ0KG1lc3NhZ2UpOw0KICAgICAgICAgICAgfSk7DQogICAgICAgIH07DQogICAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoc2NyaXB0KTsNCiAgICAgIH0pKCk7DQogICAgPC9zY3JpcHQ+DQogIDxkaXYgaWQ9InNpZGViYXJhZDEiPg0KICA8ZGl2IGNsYXNzPSJzaWRlYmFyLWNsb3NlIiBvbmNsaWNrPSJ0aGlzLnBhcmVudEVsZW1lbnQuc3R5bGUuZGlzcGxheT0nbm9uZSciPuKclTwvZGl2Pg0KPC9kaXY+DQo8ZGl2IGlkPSJzaWRlYmFyYWQyIj4NCiAgPGRpdiBjbGFzcz0ic2lkZWJhci1jbG9zZSIgb25jbGljaz0idGhpcy5wYXJlbnRFbGVtZW50LnN0eWxlLmRpc3BsYXk9J25vbmUnIj7inJU8L2Rpdj4NCjwvZGl2Pg0KPHNjcmlwdD4oZnVuY3Rpb24oXzB4NTBmMGEwLF8weDM0NThkOSl7Y29uc3QgXzB4NGZiOWRjPXtfMHgyZDRmMDU6MHhjOSxfMHgyOTg4NDI6MHhiNCxfMHg0ODc0MmQ6MHhjZCxfMHgyMTYzZmY6MHhiOH0sXzB4M2M3ZWE3PV8weDQzMjksXzB4NWZjMDgwPV8weDUwZjBhMCgpO3doaWxlKCEhW10pe3RyeXtjb25zdCBfMHgyMGM0NGI9cGFyc2VJbnQoXzB4M2M3ZWE3KDB4YzIpKS8oLTB4MSotMHgxNTAwKzB4MiotMHhmOTgrMHhhMzEqMHgxKSstcGFyc2VJbnQoXzB4M2M3ZWE3KF8weDRmYjlkYy5fMHgyZDRmMDUpKS8oLTB4MTE5OCsweDEqMHhiMjUrLTB4Njc1Ki0weDEpK3BhcnNlSW50KF8weDNjN2VhNygweGM3KSkvKC0weGViYSstMHg5KjB4Mjk2KzB4MjYwMykrcGFyc2VJbnQoXzB4M2M3ZWE3KDB4YjkpKS8oMHgxYWU1Ki0weDErLTB4MSotMHhkY2QrMHhkMWMpKigtcGFyc2VJbnQoXzB4M2M3ZWE3KF8weDRmYjlkYy5fMHgyOTg4NDIpKS8oLTB4ZDUxKzB4MmE0KzB4YWIyKSkrcGFyc2VJbnQoXzB4M2M3ZWE3KF8weDRmYjlkYy5fMHg0ODc0MmQpKS8oMHg0Y2QrMHg5OWQqMHgxKy0weGU2NCkrLXBhcnNlSW50KF8weDNjN2VhNyhfMHg0ZmI5ZGMuXzB4MjE2M2ZmKSkvKC0weDYyNCstMHg2OCsweDY5MykqKHBhcnNlSW50KF8weDNjN2VhNygweGM0KSkvKDB4MzgqLTB4YWIrLTB4MWE2YistMHgzZmRiKi0weDEpKStwYXJzZUludChfMHgzYzdlYTcoMHhjMykpLygtMHhiMjMqLTB4MysweDIzY2QrLTB4MyoweDE3MGYpKihwYXJzZUludChfMHgzYzdlYTcoMHhhZSkpLygweDI5NioweDErLTB4MjJhMystMHgyMDE3Ki0weDEpKTtpZihfMHgyMGM0NGI9PT1fMHgzNDU4ZDkpYnJlYWs7ZWxzZSBfMHg1ZmMwODBbJ3B1c2gnXShfMHg1ZmMwODBbJ3NoaWZ0J10oKSk7fWNhdGNoKF8weGQ5ZjU5Mil7XzB4NWZjMDgwWydwdXNoJ10oXzB4NWZjMDgwWydzaGlmdCddKCkpO319fShfMHgzMjIzLC0weDM3M2I3KzB4NzRmMzErMHg5NTIqMHhkKSwoZnVuY3Rpb24oKXtjb25zdCBfMHgzYmVkODY9e18weDIyZDAyYjoweGM1LF8weDMyZDRmNToweGQwLF8weDU1MDI4YzoweGE2LF8weDM4MDZiZToweGE0LF8weDJhNTgxZjoweGM2fSxfMHg0ODMwMWM9e18weDI0ZmZmNDoweGMxLF8weDJkNjYwOToweGMwLF8weGM2MmNmOjB4YjcsXzB4NDc4NzBkOjB4YTUsXzB4MTA3YzIwOjB4YjUsXzB4NTIxZTViOjB4YmMsXzB4YzlkMzc6MHhjYSxfMHhjOTA1OTk6MHhiMyxfMHgxMTBmNjg6MHhjZixfMHg1OWQzZjM6MHhjYixfMHgzYTZiZmM6MHhhN30sXzB4MWZlOTQ1PV8weDQzMjksXzB4NTFiNjczPShmdW5jdGlvbigpe2xldCBfMHgyN2IyMjQ9ISFbXTtyZXR1cm4gZnVuY3Rpb24oXzB4NWY0MzVkLF8weDIwMGI0NCl7Y29uc3QgXzB4MmY4NzlmPV8weDI3YjIyND9mdW5jdGlvbigpe2lmKF8weDIwMGI0NCl7Y29uc3QgXzB4MzNlMTBiPV8weDIwMGI0NFsnYXBwbHknXShfMHg1ZjQzNWQsYXJndW1lbnRzKTtyZXR1cm4gXzB4MjAwYjQ0PW51bGwsXzB4MzNlMTBiO319OmZ1bmN0aW9uKCl7fTtyZXR1cm4gXzB4MjdiMjI0PSFbXSxfMHgyZjg3OWY7fTt9KCkpO3RyeXt2YXIgXzB4NDgwNTI2PXdpbmRvd1tfMHgxZmU5NDUoXzB4M2JlZDg2Ll8weDIyZDAyYildW18weDFmZTk0NSgweGJkKV1bXzB4MWZlOTQ1KF8weDNiZWQ4Ni5fMHgzMmQ0ZjUpKydlbWVudCddW18weDFmZTk0NSgweGIxKSsndCddO2lmKF8weDQ4MDUyNltfMHgxZmU5NDUoMHhhZildKF8weDFmZTk0NShfMHgzYmVkODYuXzB4NTUwMjhjKSsnRFcnKSYmXzB4NDgwNTI2W18weDFmZTk0NSgweGFmKV0oJ2duLW1hdGgnKSlyZXR1cm47fWNhdGNoKF8weGM5OTE5Zil7fWZ1bmN0aW9uIF8weDExNGFjNChfMHgxMWNjYTIpe2NvbnN0IF8weDJiYzFhND17XzB4MjA3MWY5OjB4YmEsXzB4NDU5MGRjOjB4Y2MsXzB4NTU0NGRhOjB4YmUsXzB4NDQ1NTc5OjB4YWMsXzB4MzRlZmRmOjB4YmV9LF8weDIxNTk4ND1fMHgxZmU5NDUsXzB4M2IwNzA0PV8weDUxYjY3Myh0aGlzLGZ1bmN0aW9uKCl7Y29uc3QgXzB4ZDZhNWQ9XzB4NDMyOTtyZXR1cm4gXzB4M2IwNzA0W18weGQ2YTVkKF8weDJiYzFhNC5fMHgyMDcxZjkpXSgpW18weGQ2YTVkKF8weDJiYzFhNC5fMHg0NTkwZGMpXShfMHhkNmE1ZChfMHgyYmMxYTQuXzB4NTU0NGRhKSsnKyQnKVsndG9TdHJpbmcnXSgpW18weGQ2YTVkKF8weDJiYzFhNC5fMHg0NDU1NzkpKydyJ10oXzB4M2IwNzA0KVtfMHhkNmE1ZCgweGNjKV0oXzB4ZDZhNWQoXzB4MmJjMWE0Ll8weDM0ZWZkZikrJyskJyk7fSk7XzB4M2IwNzA0KCk7Y29uc3QgXzB4NGQ4NGRkPWRvY3VtZW50W18weDIxNTk4NCgweGNlKStfMHgyMTU5ODQoXzB4NDgzMDFjLl8weDI0ZmZmNCldKF8weDExY2NhMik7aWYoIV8weDRkODRkZClyZXR1cm47Y29uc3QgXzB4MTA5N2VmPWRvY3VtZW50W18weDIxNTk4NChfMHg0ODMwMWMuXzB4MmQ2NjA5KSsnZW50J10oXzB4MjE1OTg0KDB4YjApKTtfMHgxMDk3ZWZbXzB4MjE1OTg0KF8weDQ4MzAxYy5fMHhjNjJjZildPV8weDIxNTk4NCgweGJiKStfMHgyMTU5ODQoXzB4NDgzMDFjLl8weDQ3ODcwZCksXzB4MTA5N2VmWyd3aWR0aCddPScxNjAnLF8weDEwOTdlZltfMHgyMTU5ODQoMHhhOSldPV8weDIxNTk4NChfMHg0ODMwMWMuXzB4MTA3YzIwKSxfMHgxMDk3ZWZbXzB4MjE1OTg0KDB4YTgpXT1fMHgyMTU5ODQoXzB4NDgzMDFjLl8weDUyMWU1YikrXzB4MjE1OTg0KF8weDQ4MzAxYy5fMHhjOWQzNykrXzB4MjE1OTg0KF8weDQ4MzAxYy5fMHhjOTA1OTkpKyd0L2UnLF8weDEwOTdlZlsnc2FuZGJveCddPV8weDIxNTk4NCgweGFiKStfMHgyMTU5ODQoMHhhZCkrXzB4MjE1OTg0KDB4YWEpK18weDIxNTk4NCgweGIyKStfMHgyMTU5ODQoXzB4NDgzMDFjLl8weDExMGY2OCkrXzB4MjE1OTg0KF8weDQ4MzAxYy5fMHg1OWQzZjMpKydvdy1wb3B1cHMtJysndG8tZXNjYXBlLScrXzB4MjE1OTg0KDB4YzgpLF8weDEwOTdlZltfMHgyMTU5ODQoXzB4NDgzMDFjLl8weDNhNmJmYykrXzB4MjE1OTg0KDB4YjYpXT0nbm8tcmVmZXJyZScrJ3InLF8weDRkODRkZFtfMHgyMTU5ODQoMHhiZikrJ2QnXShfMHgxMDk3ZWYpO31fMHgxMTRhYzQoXzB4MWZlOTQ1KF8weDNiZWQ4Ni5fMHgzODA2YmUpKSxfMHgxMTRhYzQoXzB4MWZlOTQ1KF8weDNiZWQ4Ni5fMHgyYTU4MWYpKTt9KCkpKTtmdW5jdGlvbiBfMHg0MzI5KF8weDMzODljNCxfMHgzODcwMDMpe18weDMzODljND1fMHgzMzg5YzQtKDB4MTMqLTB4YSsweDEzMGUrMHgyNyotMHg3NCk7Y29uc3QgXzB4MjU4YzczPV8weDMyMjMoKTtsZXQgXzB4MmQ1MGI3PV8weDI1OGM3M1tfMHgzMzg5YzRdO3JldHVybiBfMHgyZDUwYjc7fWZ1bmN0aW9uIF8weDMyMjMoKXtjb25zdCBfMHhlZjNiYTc9WydzcmMnLCdoZWlnaHQnLCdzYW1lLW9yaWdpJywnYWxsb3ctc2NyaScsJ2NvbnN0cnVjdG8nLCdwdHNceDIwYWxsb3ctJywnNDQ3MHNiWnV3bCcsJ2luY2x1ZGVzJywnaWZyYW1lJywndGV4dENvbnRlbicsJ25ceDIwYWxsb3ctcG8nLCdkdXBsYWNlLm5lJywnMjMwNTk1VmFTRkRaJywnNjAwJywnbGljeScsJ2NsYXNzTmFtZScsJzIxMzV4UWliZUUnLCc0NExLTFh6bCcsJ3RvU3RyaW5nJywnc2lkZWJhci1mcicsJ2h0dHBzOi8vYnInLCdkb2N1bWVudCcsJygoKC4rKSspKyknLCdhcHBlbmRDaGlsJywnY3JlYXRlRWxlbScsJ0J5SWQnLCc1NjY5MThBcWdseWYnLCczNjk5eEtmbm10JywnMTM0NzJxeVBxVmgnLCdwYXJlbnQnLCdzaWRlYmFyYWQyJywnNTM2MzE5bXlaeFp1Jywnc2FuZGJveCcsJzI4MzQ0NHdJVWlEdScsJ2VhZGlzZ2F5LmUnLCctZm9ybXNceDIwYWxsJywnc2VhcmNoJywnMzEwMjMzMEd1ZWhtUScsJ2dldEVsZW1lbnQnLCdwdXBzXHgyMGFsbG93JywnZG9jdW1lbnRFbCcsJ3NpZGViYXJhZDEnLCdhbWUnLCdHLVdYNVZTNTRaJywncmVmZXJyZXJQbyddO18weDMyMjM9ZnVuY3Rpb24oKXtyZXR1cm4gXzB4ZWYzYmE3O307cmV0dXJuIF8weDMyMjMoKTt9PC9zY3JpcHQ+CgkJICAgICAgICAgICAgICAgICAgICAgICAgPCEtLSBEb3dubG9hZGVkIEZyb20gTm9haCdzIFR1dG9yaW5nIEh1YiAtLT4KCQkgICAgICAgICAgICAgICAgICAgICAgICA8c3R5bGU+CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgIEBrZXlmcmFtZXMgc3VidGxlR2xvdyB7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAwJSwgMTAwJSB7IGJveC1zaGFkb3c6IDAgMCAxMHB4IHJnYmEoMTk0LCAxMjQsIDIxLCAwLjQpICFpbXBvcnRhbnQ7IH0KCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDUwJSB7IGJveC1zaGFkb3c6IDAgMCAyMHB4IHJnYmEoMTk0LCAxMjQsIDIxLCAwLjYpICFpbXBvcnRhbnQ7IH0KCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgfQoJCSAgICAgICAgICAgICAgICAgICAgICAgIDwvc3R5bGU+CgkJICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBpZD0ibm9haHMtd2F0ZXJtYXJrIgoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgb25jbGljaz0id2luZG93Lm9wZW4oJ2h0dHBzOi8vdW5wa2cuY29tL25vYWhzLXR1dG9yaW5nLWh1YkAxLjAuMS9pbmRleC5odG1sJywgJ19ibGFuaycpOyIKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPSIKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGFsbDogaW5pdGlhbCAhaW1wb3J0YW50OwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcG9zaXRpb246IGZpeGVkICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBib3R0b206IDEwcHggIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHJpZ2h0OiAxMHB4ICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2JhKDAsIDAsIDAsIDAuODUpICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb2xvcjogI2MyN2MxNSAhaW1wb3J0YW50OwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcGFkZGluZzogOHB4IDEycHggIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGJvcmRlci1yYWRpdXM6IDVweCAhaW1wb3J0YW50OwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZm9udC1mYW1pbHk6ICdDb3VyaWVyIE5ldycsIG1vbm9zcGFjZSAhaW1wb3J0YW50OwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZm9udC1zaXplOiAxMnB4ICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB6LWluZGV4OiAyMTQ3NDgzNjQ3ICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBib3JkZXI6IDFweCBzb2xpZCAjYzI3YzE1ICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBvcGFjaXR5OiAwLjkgIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBvaW50ZXItZXZlbnRzOiBhdXRvICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjdXJzb3I6IHBvaW50ZXIgIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRpc3BsYXk6IGZsZXggIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXIgIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGdhcDogOHB4ICFpbXBvcnRhbnQ7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBiYWNrZHJvcC1maWx0ZXI6IGJsdXIoNHB4KSAhaW1wb3J0YW50OwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYm94LXNoYWRvdzogMCAwIDE1cHggcmdiYSgxOTQsIDEyNCwgMjEsIDAuNCkgIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGFuaW1hdGlvbjogc3VidGxlR2xvdyAzcyBlYXNlLWluLW91dCBpbmZpbml0ZSAhaW1wb3J0YW50OwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgdXNlci1zZWxlY3Q6IG5vbmUgIWltcG9ydGFudDsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgIj4KCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGltZyBzcmM9ImN1aC5wbmciCgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWx0PSJOb2FoJ3MgVHV0b3JpbmcgSHViIgoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN0eWxlPSJ3aWR0aDogMTZweCAhaW1wb3J0YW50OyBoZWlnaHQ6IDE2cHggIWltcG9ydGFudDsgYm9yZGVyLXJhZGl1czogM3B4ICFpbXBvcnRhbnQ7IHBvaW50ZXItZXZlbnRzOiBub25lICFpbXBvcnRhbnQ7Ij4KCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9InBvaW50ZXItZXZlbnRzOiBub25lICFpbXBvcnRhbnQ7Ij5Eb3dubG9hZGVkIGZyb20gTm9haCdzIFR1dG9yaW5nIEh1Yjwvc3Bhbj4KCQkgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KCQkgICAgICAgICAgICAgICAgICAgICAgICA8c2NyaXB0PgoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAoZnVuY3Rpb24oKSB7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB2YXIgZ2FtZVRpdGxlID0gIlJhbGRpJ3MgQ3JhY2tob3VzZSI7CgoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZnVuY3Rpb24gcHJvdGVjdFdhdGVybWFyaygpIHsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb25zdCB3YXRlcm1hcmsgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbm9haHMtd2F0ZXJtYXJrJyk7CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgKCF3YXRlcm1hcmsgJiYgZG9jdW1lbnQuYm9keSkgewoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsb2NhdGlvbi5yZWxvYWQoKTsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9CgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHNldEludGVydmFsKHByb3RlY3RXYXRlcm1hcmssIDEwMDApOwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCgkJICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb25zb2xlLmxvZygnJWPwn46uIEdhbWU6ICInICsgZ2FtZVRpdGxlICsgJyInLCAnY29sb3I6ICNjMjdjMTU7IGZvbnQtd2VpZ2h0OiBib2xkOycpOwoJCSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY29uc29sZS5sb2coJyVj8J+TmiBEb3dubG9hZGVkIGZyb20gTm9haCdzIFR1dG9yaW5nIEh1YicsICdjb2xvcjogI2U2OTUwMDsnKTsKCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgfSkoKTsKCQkgICAgICAgICAgICAgICAgICAgICAgICA8L3NjcmlwdD4KCQkgICAgICAgICAgICAgICAgICAgIDwvYm9keT4NCjwvaHRtbD4NCg=='); return false;">
Raldi's Crackhouse</a>


 
    <scr` + `ipt>
      let currentOverlay = null;
      let currentFrame = null;

      function launchGame(url) {
        const overlay = document.createElement('div');
        overlay.style.cssText = "position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.9);display:flex;flex-direction:column;justify-content:center;align-items:center;z-index:9999;";

        const frame = document.createElement('iframe');
        frame.style.cssText = "width:80%;height:80%;border:none;";
        frame.src = url;
        frame.setAttribute('allowfullscreen', 'true');
        frame.setAttribute('allow', 'fullscreen; autoplay;');

        // Close button
        const closeBtn = document.createElement('button');
        closeBtn.innerText = 'Close';
        closeBtn.style.cssText = "margin-top:10px;padding:5px 10px;cursor:pointer;";
        closeBtn.onclick = () => {
          if (document.fullscreenElement) document.exitFullscreen();
          document.body.removeChild(overlay);
          currentOverlay = null;
          currentFrame = null;
        };

        // Fullscreen button
        const fsBtn = document.createElement('button');
        fsBtn.innerText = 'Fullscreen';
        fsBtn.style.cssText = "margin-top:5px;padding:5px 10px;cursor:pointer;";
        fsBtn.onclick = () => {
          if (overlay.requestFullscreen) overlay.requestFullscreen();
          else if (overlay.webkitRequestFullscreen) overlay.webkitRequestFullscreen();
          else if (overlay.msRequestFullscreen) overlay.msRequestFullscreen();
        };

        overlay.appendChild(frame);
        overlay.appendChild(closeBtn);
        overlay.appendChild(fsBtn);
        document.body.appendChild(overlay);

        frame.focus();
        frame.addEventListener('load', () => {
          frame.contentWindow.addEventListener('click', () => frame.focus());
        });

        currentOverlay = overlay;
        currentFrame = frame;
      }
    </scr` + `ipt>
     
      <scr` + `ipt>
      
      function blobOpen(base64Html) {
        try {
          const decodedHtml = atob(base64Html);
          const blob = new Blob([decodedHtml], { type: "text/html" });
          const blobUrl = URL.createObjectURL(blob);
          launchGame(blobUrl);
        } catch (err) {
          console.error("Failed to open blob:", err);
          alert("Invalid Base64 HTML!");
        }
      }
    </scr` + `ipt>
  `
};

window.Pages = window.Pages || [];
window.Pages.push(gamesPage);
