const unblockersPage = {
    id: "unblockers",
    title: "unblockers",
    html: `
      <h1>unblockers</h1>
<a href="javascript:(function(){
  var base64='PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KPHRpdGxlPnZpZXdlci1jbGk8L3RpdGxlPgo8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMCI+CjxzdHlsZT4KYm9keSB7CiAgICBtYXJnaW46IDA7CiAgICBiYWNrZ3JvdW5kOiAjMDAwOwogICAgY29sb3I6ICMwMGZmODg7CiAgICBmb250LWZhbWlseTogbW9ub3NwYWNlOwp9CgojdGVybWluYWwgewogICAgcGFkZGluZzogMTVweDsKICAgIGhlaWdodDogNjB2aDsKICAgIG92ZXJmbG93LXk6IGF1dG87CiAgICB3aGl0ZS1zcGFjZTogcHJlLXdyYXA7Cn0KCiNpbnB1dC1saW5lIHsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBwYWRkaW5nOiAxMHB4OwogICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkICMwMDMzMjI7Cn0KCiNwcm9tcHQgewogICAgbWFyZ2luLXJpZ2h0OiA4cHg7Cn0KCiNjbWQgewogICAgZmxleDogMTsKICAgIGJhY2tncm91bmQ6IGJsYWNrOwogICAgYm9yZGVyOiBub25lOwogICAgY29sb3I6ICMwMGZmODg7CiAgICBvdXRsaW5lOiBub25lOwogICAgZm9udC1mYW1pbHk6IG1vbm9zcGFjZTsKfQoKI3ZpZGVvcyB7CiAgICBwYWRkaW5nOiAxMHB4Owp9CgppZnJhbWUgewogICAgd2lkdGg6IDEwMCU7CiAgICBoZWlnaHQ6IDMwMHB4OwogICAgYm9yZGVyOiBub25lOwogICAgbWFyZ2luLXRvcDogMTBweDsKfQo8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5PgoKPGRpdiBpZD0idGVybWluYWwiPjwvZGl2PgoKPGRpdiBpZD0iaW5wdXQtbGluZSI+CiAgICA8ZGl2IGlkPSJwcm9tcHQiPj48L2Rpdj4KICAgIDxpbnB1dCBpZD0iY21kIiBhdXRvY29tcGxldGU9Im9mZiI+CjwvZGl2PgoKPGRpdiBpZD0idmlkZW9zIj48L2Rpdj4KCjxzY3JpcHQ+CmNvbnN0IHRlcm0gPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgidGVybWluYWwiKTsKY29uc3QgaW5wdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiY21kIik7CmNvbnN0IHZpZGVvcyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJ2aWRlb3MiKTsKCmNvbnN0IGJhc2UgPSAiaHR0cHM6Ly93d3cueW91dHViZS1ub2Nvb2tpZS5jb20vZW1iZWQvIjsKY29uc3QgZW5kID0gIj9hdXRvcGxheT0xJnJlbD0wJm1vZGVzdGJyYW5kaW5nPTEiOwoKLy8gLS0tIFRlcm1pbmFsIGxvZ2dpbmcgLS0tCmZ1bmN0aW9uIGxvZyh0ZXh0LCB0eXBlPSJJTkZPIikgewogICAgY29uc3QgbGluZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoImRpdiIpOwogICAgbGluZS50ZXh0Q29udGVudCA9IGBbJHt0eXBlfV0gJHt0ZXh0fWA7CiAgICB0ZXJtLmFwcGVuZENoaWxkKGxpbmUpOwogICAgdGVybS5zY3JvbGxUb3AgPSB0ZXJtLnNjcm9sbEhlaWdodDsKfQoKLy8gSG9vayBjb25zb2xlLmxvZyBpbnRvIHRlcm1pbmFsCmNvbnN0IG9sZExvZyA9IGNvbnNvbGUubG9nOwpjb25zb2xlLmxvZyA9IGZ1bmN0aW9uKC4uLmFyZ3MpIHsKICAgIG9sZExvZyguLi5hcmdzKTsKICAgIGxvZyhhcmdzLmpvaW4oIiAiKSwgIkxPRyIpOwp9OwoKLy8gLS0tIFlvdVR1YmUgSUQgZXh0cmFjdGlvbiAtLS0KZnVuY3Rpb24gZ2V0WW91VHViZUlEKHVybCkgewogICAgY29uc3QgcmVnRXhwID0gLyg/OnlvdXR1YmVcLmNvbVwvKD86d2F0Y2hcP3Y9fGVtYmVkXC98c2hvcnRzXC8pfHlvdXR1XC5iZVwvKShbYS16QS1aMC05Xy1dezExfSkvOwogICAgY29uc3QgbWF0Y2ggPSB1cmwubWF0Y2gocmVnRXhwKTsKICAgIHJldHVybiBtYXRjaCA/IG1hdGNoWzFdIDogbnVsbDsKfQoKLy8gLS0tIExvYWQgdmlkZW8gLS0tCmZ1bmN0aW9uIGxvYWRWaWRlbyh1cmwpIHsKICAgIGxvZygiUGFyc2luZyBVUkwuLi4iLCAiSU5GTyIpOwoKICAgIGNvbnN0IGlkID0gZ2V0WW91VHViZUlEKHVybCk7CiAgICBpZiAoIWlkKSB7CiAgICAgICAgbG9nKCJJbnZhbGlkIFVSTCIsICJFUlJPUiIpOwogICAgICAgIHJldHVybjsKICAgIH0KCiAgICBsb2coIkNvbm5lY3RpbmcgdG8gZW5kcG9pbnQuLi4iLCAiQ09OTkVDVCIpOwoKICAgIHNldFRpbWVvdXQoKCkgPT4gewogICAgICAgIGxvZygiRmV0Y2hpbmcgc3RyZWFtLi4uIiwgIkZFVENIIik7CgogICAgICAgIGNvbnN0IGlmcmFtZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoImlmcmFtZSIpOwogICAgICAgIGlmcmFtZS5zcmMgPSBiYXNlICsgaWQgKyBlbmQ7CgogICAgICAgIHZpZGVvcy5wcmVwZW5kKGlmcmFtZSk7CgogICAgICAgIGxvZygiUGxheWJhY2sgc3RhcnRlZCIsICJTVUNDRVNTIik7CiAgICB9LCA1MDApOwp9CgovLyAtLS0gQ29tbWFuZCBoYW5kbGVyIC0tLQpmdW5jdGlvbiBydW5Db21tYW5kKGNtZCkgewogICAgbG9nKCI+ICIgKyBjbWQsICJDTUQiKTsKCiAgICBjb25zdCBwYXJ0cyA9IGNtZC5zcGxpdCgiICIpOwogICAgY29uc3QgYmFzZUNtZCA9IHBhcnRzWzBdOwoKICAgIHN3aXRjaChiYXNlQ21kKSB7CiAgICAgICAgY2FzZSAiaGVscCI6CiAgICAgICAgICAgIGxvZygiQ29tbWFuZHM6IiwgIklORk8iKTsKICAgICAgICAgICAgbG9nKCJsb2FkIDx1cmw+ICAtIGxvYWQgdmlkZW8iLCAiSU5GTyIpOwogICAgICAgICAgICBsb2coImNsZWFyICAgICAgIC0gY2xlYXIgdGVybWluYWwiLCAiSU5GTyIpOwogICAgICAgICAgICBicmVhazsKCiAgICAgICAgY2FzZSAibG9hZCI6CiAgICAgICAgICAgIGlmICghcGFydHNbMV0pIHsKICAgICAgICAgICAgICAgIGxvZygiTWlzc2luZyBVUkwiLCAiRVJST1IiKTsKICAgICAgICAgICAgICAgIHJldHVybjsKICAgICAgICAgICAgfQogICAgICAgICAgICBsb2FkVmlkZW8ocGFydHNbMV0pOwogICAgICAgICAgICBicmVhazsKCiAgICAgICAgY2FzZSAiY2xlYXIiOgogICAgICAgICAgICB0ZXJtLmlubmVySFRNTCA9ICIiOwogICAgICAgICAgICBicmVhazsKCiAgICAgICAgZGVmYXVsdDoKICAgICAgICAgICAgbG9nKCJVbmtub3duIGNvbW1hbmQiLCAiRVJST1IiKTsKICAgIH0KfQoKLy8gLS0tIElucHV0IGhhbmRsaW5nIC0tLQppbnB1dC5hZGRFdmVudExpc3RlbmVyKCJrZXlkb3duIiwgZSA9PiB7CiAgICBpZiAoZS5rZXkgPT09ICJFbnRlciIpIHsKICAgICAgICBjb25zdCB2YWx1ZSA9IGlucHV0LnZhbHVlLnRyaW0oKTsKICAgICAgICBpZiAodmFsdWUpIHJ1bkNvbW1hbmQodmFsdWUpOwogICAgICAgIGlucHV0LnZhbHVlID0gIiI7CiAgICB9Cn0pOwoKLy8gQm9vdCBtZXNzYWdlCmxvZygidmlld2VyLWNsaSBpbml0aWFsaXplZCIsICJCT09UIik7CmxvZygidHlwZSAnaGVscCcgZm9yIGNvbW1hbmRzIiwgIkJPT1QiKTsKPC9zY3JpcHQ+Cgo8L2JvZHk+CjwvaHRtbD4=';
  var html=atob(base64);
  var blob=new Blob([html],{type:'text/html'});
  var url=URL.createObjectURL(blob);
  var m=document.createElement('div');
  m.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.7);display:flex;justify-content:center;align-items:center;z-index:9999;';
  var f=document.createElement('iframe');
  f.style.cssText='width:80%;height:80%;border:none;';
  f.src=url;
  var b=document.createElement('button');
  b.innerText='Close';
  b.style.cssText='position:absolute;top:10px;right:10px;padding:5px 10px;cursor:pointer;z-index:10;';
  b.onclick=function(){document.body.removeChild(m); URL.revokeObjectURL(url);};
  m.appendChild(b);
  m.appendChild(f);
  document.body.appendChild(m);
})()">viewer-cli (youtube bypass)</a>
      
    `
};

window.Pages = window.Pages || [];
window.Pages.push(unblockersPage);
